Repository WDAqua/Qanary-question-answering-components, pull requests merged in 2023-08, with the labels that each got.

#298 [Snyk] Upgrade org.springdoc:springdoc-openapi-ui from 1.6.14 to 1.7.0
  qanary-component-LD-Shuyo/pom.xml
Labels: dependencies

#297 [Snyk] Upgrade org.springdoc:springdoc-openapi-data-rest from 1.6.14 to 1.7.0
  qanary-component-QE-Wikidata/pom.xml
Labels: dependencies

#296 Remove `org.apache.jena` from components
  qanary-component-NED-DBpediaSpotlight/pom.xml
  qanary-component-NED-DBpediaSpotlight/src/main/java/eu/wdaqua/qanary/component/dbpediaspotlight/ned/Application.java
  qanary-component-NED-DBpediaSpotlight/src/main/java/eu/wdaqua/qanary/component/dbpediaspotlight/ned/DBpediaSpotlightNED.java
  qanary-component-NED-DBpediaSpotlight/src/main/java/eu/wdaqua/qanary/component/dbpediaspotlight/ned/DBpediaSpotlightServiceFetcher.java
  qanary-component-NED-DBpediaSpotlight/src/test/java/eu/wdaqua/qanary/component/dbpediaspotlight/ned/DBpediaSpotlightServiceFetcherTest.java
  qanary-component-NERD-SMAPH/pom.xml
  qanary-component-QBE-QAnswer/pom.xml
  qanary-component-QE-SparqlExecuter/pom.xml
  qanary-component-QE-SparqlExecuter/src/main/java/eu/wdaqua/qanary/sparqlexecuter/SparqlExecuter.java
  qanary-component-QE-SparqlExecuter/src/test/java/eu/wdaqua/qanary/sparqlexecuter/QanaryServiceControllerTest.java
  qanary-component-QE-SparqlExecuter/src/test/java/eu/wdaqua/qanary/sparqlexecuter/SparqlExecuterTest.java
Labels: enhancement, dependencies

#299 [Snyk] Upgrade org.springdoc:springdoc-openapi-ui from 1.6.15 to 1.7.0
  qanary-component-QB-RuBQWrapper/pom.xml
Labels: dependencies

#289 Extend platypus component
  qanary-component-QB-PlatypusWrapper/README.adoc
  qanary-component-QB-PlatypusWrapper/pom.xml
  qanary-component-QB-PlatypusWrapper/src/main/java/eu/wdaqua/qanary/component/platypuswrapper/qb/PlatypusQueryBuilder.java
  qanary-component-QB-PlatypusWrapper/src/main/java/eu/wdaqua/qanary/component/platypuswrapper/qb/PlatypusQueryBuilderController.java
  qanary-component-QB-PlatypusWrapper/src/main/java/eu/wdaqua/qanary/component/platypuswrapper/qb/messages/DataNotProcessableException.java
  qanary-component-QB-PlatypusWrapper/src/main/java/eu/wdaqua/qanary/component/platypuswrapper/qb/messages/NoLiteralTypeResourceFoundException.java
  qanary-component-QB-PlatypusWrapper/src/main/java/eu/wdaqua/qanary/component/platypuswrapper/qb/messages/PlatypusResult.java
  qanary-component-QB-PlatypusWrapper/src/main/java/eu/wdaqua/qanary/component/platypuswrapper/qb/messages/ProcessedResult.java
  qanary-component-QB-PlatypusWrapper/src/main/resources/component-description.ttl
  qanary-component-QB-PlatypusWrapper/src/main/resources/config/application.properties
  qanary-component-QB-PlatypusWrapper/src/test/java/eu/wdaqua/qanary/component/platypuswrapper/qb/MockPlatypusQueryBuilderTest.java
  qanary-component-QB-PlatypusWrapper/src/test/java/eu/wdaqua/qanary/component/platypuswrapper/qb/PlatypusQueryBuilderTest.java
  qanary-component-QB-PlatypusWrapper/src/test/java/eu/wdaqua/qanary/component/platypuswrapper/qb/PlatypusTestConfiguration.java
Labels: enhancement

#302 [Snyk] Upgrade org.springdoc:springdoc-openapi-data-rest from 1.6.15 to 1.7.0
  qanary-component-NED-DBpediaSpotlight/pom.xml
Labels: dependencies

#301 [Snyk] Upgrade org.springdoc:springdoc-openapi-ui from 1.6.14 to 1.7.0
  qanary-component-QB-TeBaQaWrapper/pom.xml
Labels: dependencies

#303 Qanary component qanary-component-QB-DateOfDeathDBpedia
  qanary-component-QB-DateOfDeathDBpedia/Dockerfile
  qanary-component-QB-DateOfDeathDBpedia/README.adoc
  qanary-component-QB-DateOfDeathDBpedia/pom.xml
  qanary-component-QB-DateOfDeathDBpedia/src/main/java/eu/wdaqua/qanary/component/dateofdeathrealpersons/qb/Application.java
  qanary-component-QB-DateOfDeathDBpedia/src/main/java/eu/wdaqua/qanary/component/dateofdeathrealpersons/qb/QueryBuilderDateOfDeathDBpedia.java
  qanary-component-QB-DateOfDeathDBpedia/src/main/java/eu/wdaqua/qanary/component/dateofdeathrealpersons/qb/controller/QueryBuilderDateOfDeathDBpediaController.java
  qanary-component-QB-DateOfDeathDBpedia/src/main/java/eu/wdaqua/qanary/component/dateofdeathrealpersons/qb/controller/WebServerFActoryCustomizer.java
  qanary-component-QB-DateOfDeathDBpedia/src/main/resources/config/application.properties
  qanary-component-QB-DateOfDeathDBpedia/src/main/resources/queries/README.md
  qanary-component-QB-DateOfDeathDBpedia/src/main/resources/queries/dbpedia_query.rq
  qanary-component-QB-DateOfDeathDBpedia/src/main/resources/queries/fetch_required_annotations.rq
  qanary-component-QB-DateOfDeathDBpedia/src/main/resources/queries/insert_one_annotation.rq
  qanary-component-QB-DateOfDeathDBpedia/src/main/resources/templates/description.html
  qanary-component-QB-DateOfDeathDBpedia/src/test/java/eu/wdaqua/qanary/component/mypackage/QanaryServiceQueryBuilderDateOfDeathDBpediaControllerTest.java
  qanary-component-QB-DateOfDeathDBpedia/src/test/java/eu/wdaqua/qanary/component/mypackage/TupleTestObject.java
  service_config/files/qb-dateofdeathdbpedia
  service_config/service_config.json
Labels: new component

#285 Refactor Python MT components
  qanary-component-MT-Python-HelsinkiNLP/Dockerfile
  qanary-component-MT-Python-HelsinkiNLP/README.md
  qanary-component-MT-Python-HelsinkiNLP/component/__init__.py
  qanary-component-MT-Python-HelsinkiNLP/requirements.txt
  qanary-component-MT-Python-HelsinkiNLP/tests/test_mt_helsinky_nlp.py
  qanary-component-MT-Python-LibreTranslate/README.md
  qanary-component-MT-Python-LibreTranslate/component/__init__.py
  qanary-component-MT-Python-LibreTranslate/docker-compose.yml
  qanary-component-MT-Python-LibreTranslate/requirements.txt
  qanary-component-MT-Python-LibreTranslate/run.py
  qanary-component-MT-Python-LibreTranslate/tests/test_mt_libretranslate.py
  qanary-component-MT-Python-MBart/Dockerfile
  qanary-component-MT-Python-MBart/README.md
  qanary-component-MT-Python-MBart/component/__init__.py
  qanary-component-MT-Python-MBart/docker-compose.yml
  qanary-component-MT-Python-MBart/requirements.txt
  qanary-component-MT-Python-MBart/run.py
  qanary-component-MT-Python-MBart/tests/test_mt_mbart_nlp.py
  qanary-component-MT-Python-NLLB/Dockerfile
  qanary-component-MT-Python-NLLB/README.md
  qanary-component-MT-Python-NLLB/component/__init__.py
  qanary-component-MT-Python-NLLB/docker-compose.yml
  qanary-component-MT-Python-NLLB/requirements.txt
  qanary-component-MT-Python-NLLB/run.py
  qanary-component-MT-Python-NLLB/tests/test_mt_nllb.py
Labels: enhancement
